### ISSUE TITLE
Reynolds Dataset

### ISSUE THREAD

**Issue by Adesoji1** [ffletcherr/face-recognition-liveness#2]
will the dataset contain both the real and fake images when creating a facebank?

**Comment by ffletcherr** [comment]
@Adesoji1 

The facebank (csv files) does not serve any purpose other than indentity verification. So you can fill it with both live and fake data.

**Comment by Adesoji1** [comment]
@ffletcherr . How do i Train with my dataset? In addition i tested the model when i ran the python webcam.py and most of the predictions were below 0.03 for a real object and for a spoof image, i got 0.23 upwards, how do i improve the model performance?

**Comment by ffletcherr** [comment]
@Adesoji1 

The identity recognition pre-trained model came from the [faceNet-PyTorch](https://github.com/timesler/facenet-pytorch#pretrained-models) repo. You can read this for more detail. There is no need to train it again, so we only use it to achieve the embedding vector of a face and compare that with stored vectors of database faces in CSV files (and you can create your CSV file for your images using provided [create_facebank.py](https://github.com/ffletcherr/face-recognition-liveness/blob/main/create_facebank.py) script). 

The liveness model is borrowed from the [deepPixBis](https://www.idiap.ch/software/bob/docs/bob/bob.paper.deep_pix_bis_pad.icb2019/master/pix_bis.html#using-pretrained-models) work. The authors provided some [pre-trained models](http://www.idiap.ch/software/bob/data/bob/bob.paper.deep_pix_bis_pad.icb2019/master/Pretrained_models_DeepPixBiS.tar.bz2), and these models have different performances in different lighting situations. You can test them and use the best for your condition. For this reason PyTorch models must be converted to onnx models.

**Comment by Adesoji1** [comment]
@ffletcherr Thanks, issue resolved
