### ISSUE TITLE
Convert Pytoch .pth to .onnx

### ISSUE THREAD

**Issue by evandromoura** [ffletcherr/face-recognition-liveness#4]
Hello my friend
How do I convert .pth files to onnx?

I want to test other protocols. Because I have a case where the client managed to circumvent liveness with a fake photo.

**Comment by ffletcherr** [comment]
@evandromoura 
Use this script :

https://github.com/ffletcherr/face-recognition-liveness/blob/stable/code-liveness-DeepPixBis-2021-01-10/utils.py

**Comment by evandromoura** [comment]
Thank you man
The conversion worked
